[project]
name = "rl"
version = "0.1.0"
authors = [
    { name = "Faiz Surani", email = "faiz@law.stanford.edu" },
]
description = "A CLI for various RegLab / Sherlock tasks"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.6"
dependencies = [
    "click",
    "rich",
    "pexpect",
    "pyopt",
    "requests",
    "pycryptodome",
    "appdirs",
]

[project.urls]
homepage = "https://github.com/reglab/rl"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
rl = "rl.cli:cli"

[tool.setuptools]
packages = ["rl"]

[tool.isort]
profile = "black"
src_paths = ["rl"]
skip_gitignore = true
