[project]
name = "rl"
version = "0.5.0"
authors = [
    { name = "Faiz Surani", email = "faiz@law.stanford.edu" },
    { name = "Varun Magesh", email="vim@law.stanford.edu" }
]
description = "A CLI for various RegLab / Sherlock tasks"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.9"
dependencies = [
    "click",
    "rich",
    "tqdm",
    "pexpect",
    "pyotp",
    "requests",
    "pycryptodome",
    "appdirs",
    "regex",
    "questionary",
    "StrEnum",
    "python-dotenv",
    "matplotlib",
    "pandas",
    "pyspark",
    "unidecode",
]

[project.optional-dependencies]
llm = [
    "vllm==0.4.1; platform_system == 'Linux'",
    "transformers",
    "torch",
    "peft",
    "trl",
    "datasets",
    "wandb",
    "huggingface_hub",
    "modal",
    "anthropic",
    "openai",
]
dev = [
    "build",
    "pygithub",
    "pyinstaller",
    "black",
    "isort",
    "mypy",
]

[project.urls]
homepage = "https://github.com/ProbablyFaiz/rl"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
rl = "rl.cli.main:cli"

[tool.setuptools.packages]
find = {}

[tool.isort]
profile = "black"
src_paths = ["rl"]
skip_gitignore = true

[tool.mypy]
disable_error_code = ["import", "override"]

[tool.ruff.lint]
extend-select = ["I"]
extend-ignore = ["F401"]
