name: Build and Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    environment: Publish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install .
        pip install cibuildwheel

    - name: Build package
      run: |
        cibuildwheel --output-dir dist

    - name: Publish package
      if: startsWith(matrix.os, 'ubuntu-')  # Publish only once
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*
